-- create database Porteria;
-- use Porteria;

-- CREATE TABLE IF NOT EXISTS Empleado (
-- 	id INTEGER NOT NULL AUTO_INCREMENT,
-- 	Apellido VARCHAR(50) NOT NULL,
-- 	Nombre VARCHAR(50) NOT NULL,
-- 	Correo VARCHAR(150) NOT NULL,
-- 	Telefono VARCHAR(15) NOT NULL,
-- 	Estado BOOLEAN NOT NULL DEFAULT True,
-- 	PRIMARY KEY(id)
-- );

-- CREATE TABLE IF NOT EXISTS Usuario (
-- 	id INTEGER NOT NULL AUTO_INCREMENT,
-- 	NombreUsuario VARCHAR(50) NOT NULL UNIQUE,
-- 	Contraseña VARCHAR(255) NOT NULL,
-- 	Rol ENUM('admin', 'supervisor', 'usuario', 'propietario') NOT NULL,
-- 	Estado BOOLEAN NOT NULL,
-- 	id_empleado INTEGER NOT NULL unique,		
-- 	PRIMARY KEY(id),
--     foreign key(id_empleado) references Empleado(id)
-- );

-- CREATE TABLE IF NOT EXISTS Eventos(
-- 	id integer not null auto_increment,
--     tipo enum('ingreso','egreso','paqueteria','visitas','otros') not null,
--     fecha datetime default current_timestamp not null,
--     observaciones varchar(500),
--     imagen varchar(255),
--     id_usuario integer not null,
--     primary key(id),
--     foreign key(id_usuario) references Usuario(id),
--     INDEX(fecha)
-- );

-- #ALTER TABLE Eventos ADD column imagen varchar(255) default null;

-- # TABLE Usuario MODIFY Rol ENUM('admin', 'supervisor', 'usuario', 'propietario') NOT NULL;

-- SHOW COLUMNS FROM Usuario LIKE 'Rol';

-- select * from empleado;

-- insert into empleado(apellido,nombre,correo,telefono)
-- values
-- ('grillo','pepe','pepe@gmail.com','3816328144');

-- select * from usuario;

-- update usuario set Contraseña = '$2a$12$15JXJaBcPt./ycSvSKbQ.eg7tFZ4yUmMKr8Obc9QZOnLFmqK0XG26' WHERE id = 1;

-- insert into usuario(nombreusuario,contraseña,rol,estado,id_empleado)
-- values
-- ('1234','$2a$12$15JXJaBcPt./ycSvSKbQ.eg7tFZ4yUmMKr8Obc9QZOnLFmqK0XG26','admin',1,1);

-- select * from Eventos; 
-- insert into Eventos(tipo,observaciones,id_usuario)
-- values
-- ('paqueteria','Paquete de ML para Diego de la Vega, del 3ro C',1)


-- MySQL Script generated by MySQL Workbench
-- Wed Nov 26 15:11:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema porteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema porteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `porteria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `porteria` ;

-- -----------------------------------------------------
-- Table `porteria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porteria`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Apellido` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Correo` VARCHAR(150) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Estado` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `porteria`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porteria`.`propietario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Apellido` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `DNI` VARCHAR(15) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Estado` TINYINT(1) NOT NULL DEFAULT '1',
  `Departamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `DNI` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `porteria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porteria`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Rol` ENUM('admin', 'supervisor', 'usuario', 'propietario') NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  `id_empleado` INT NULL DEFAULT NULL,
  `id_propietario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NombreUsuario` (`NombreUsuario` ASC) VISIBLE,
  UNIQUE INDEX `id_empleado` (`id_empleado` ASC) VISIBLE,
  UNIQUE INDEX `id_propietario` (`id_propietario` ASC) VISIBLE,
  INDEX `NombreUsuario_2` (`NombreUsuario` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `porteria`.`empleado` (`id`),
  CONSTRAINT `usuario_ibfk_2`
    FOREIGN KEY (`id_propietario`)
    REFERENCES `porteria`.`propietario` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `porteria`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS eventos (
  id INT NOT NULL AUTO_INCREMENT,
  tipo ENUM('ingreso', 'egreso', 'paqueteria', 'visitas', 'otros') NOT NULL,
  fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observaciones VARCHAR(500) NULL DEFAULT NULL,
  imagen VARCHAR(255) NULL DEFAULT NULL,
  id_usuario INT NOT NULL,
  id_propietario INT NULL,
  PRIMARY KEY (id),
  INDEX id_usuario (id_usuario ASC),
  INDEX fecha (fecha ASC),
  INDEX id_propietario (id_propietario ASC),
  FOREIGN KEY (id_usuario) REFERENCES usuario (id),
  FOREIGN KEY (id_propietario) REFERENCES propietario (id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `porteria`.`novedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porteria`.`novedades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('empleado', 'propietario', 'todos') NOT NULL,
  `Fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Titulo` VARCHAR(50) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  `Estado` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `porteria`.`reclamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porteria`.`reclamo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('portero', 'vecinos', 'edificio', 'otros') NOT NULL,
  `Fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Mensaje` VARCHAR(500) NOT NULL,
  `Foto` VARCHAR(255) NULL DEFAULT NULL,
  `Estado` TINYINT(1) NOT NULL DEFAULT '1',
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `reclamo_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `porteria`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;